### ISSUE TITLE
ImportError CFGDenoisedParams

### ISSUE THREAD

**Issue by derekwitucki** [opparco/stable-diffusion-webui-two-shot#19]
Error in console keeping script from loading.

`Error loading script: two_shot.py
Traceback (most recent call last):
  File "G:\automatic1111\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "G:\automatic1111\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\automatic1111\stable-diffusion-webui\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py", line 11, in <module>
    from modules.script_callbacks import CFGDenoisedParams, on_cfg_denoised
ImportError: cannot import name 'CFGDenoisedParams' from 'modules.script_callbacks' (G:\automatic1111\stable-diffusion-webui\modules\script_callbacks.py)
`

**Comment by coronet1127** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/script_callbacks.py

Place this Python file in the modules folder.

Keep a copy of the original Python file, just in case

**Comment by zircher** [comment]
This also worked for my loading problem.  Thank you!

**Comment by pidanchou** [comment]
thank you

> https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/script_callbacks.py
> 
> Place this Python file in the modules folder.
> 
> Keep a copy of the original Python file, just in case

coooool, fix it, thank you!!
