### ISSUE TITLE
what is this error?

### ISSUE THREAD

**Issue by Head-Hunter-is-OP** [opparco/stable-diffusion-webui-two-shot#2]
i ran the web ui user and it gives me this error 

Error loading script: two_shot.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/stable-diffusion-webui/extensions/stable-diffusion-webui-two-shot/scripts/two_shot.py", line 10, in <module>
    from modules.script_callbacks import CFGDenoisedParams, on_cfg_denoised
ImportError: cannot import name 'CFGDenoisedParams' from 'modules.script_callbacks' (/content/stable-diffusion-webui/modules/script_callbacks.py)

**Comment by ddPn08** [comment]
Did you run this command?
```
git apply --ignore-whitespace extensions/stable-diffusion-webui-two-shot/cfg_denoised_callback-ea9bd9fc.patch
```

**Comment by Yodokoro** [comment]
I have same error.
I think the patch is actually applied but it still happens.
I tried re-download webui for new directory and install cleanly, but same error.

webui version:
3715ece0adce7bf7c5e9c5ab3710b2fdc3848f39
(master branch 2023/02/13 14:12:51)

git diff:
```
diff --git a/modules/script_callbacks.py b/modules/script_callbacks.py
index 4bb45ec..a47e117 100644
--- a/modules/script_callbacks.py
+++ b/modules/script_callbacks.py
@@ -46,6 +46,18 @@ class CFGDenoiserParams:
         """Total number of sampling steps planned"""


+class CFGDenoisedParams:
+    def __init__(self, x, sampling_step, total_sampling_steps):
+        self.x = x
+        """Latent image representation in the process of being denoised"""
+
+        self.sampling_step = sampling_step
+        """Current Sampling step number"""
+
+        self.total_sampling_steps = total_sampling_steps
+        """Total number of sampling steps planned"""
+
+
 class UiTrainTabParams:
     def __init__(self, txt2img_preview_params):
         self.txt2img_preview_params = txt2img_preview_params
@@ -68,6 +80,7 @@ callback_map = dict(
     callbacks_before_image_saved=[],
     callbacks_image_saved=[],
     callbacks_cfg_denoiser=[],
+    callbacks_cfg_denoised=[],
     callbacks_before_component=[],
     callbacks_after_component=[],
     callbacks_image_grid=[],
@@ -150,6 +163,14 @@ def cfg_denoiser_callback(params: CFGDenoiserParams):
             report_exception(c, 'cfg_denoiser_callback')


+def cfg_denoised_callback(params: CFGDenoisedParams):
+    for c in callback_map['callbacks_cfg_denoised']:
+        try:
+            c.callback(params)
+        except Exception:
+            report_exception(c, 'cfg_denoised_callback')
+
+
 def before_component_callback(component, **kwargs):
     for c in callback_map['callbacks_before_component']:
         try:
@@ -283,6 +304,14 @@ def on_cfg_denoiser(callback):
     add_callback(callback_map['callbacks_cfg_denoiser'], callback)


+def on_cfg_denoised(callback):
+    """register a function to be called in the kdiffussion cfg_denoiser method after building the inner model inputs.
+    The callback is called with one argument:
+        - params: CFGDenoisedParams - parameters to be passed to the inner model and sampling state details.
+    """
+    add_callback(callback_map['callbacks_cfg_denoised'], callback)
+
+
 def on_before_component(callback):
     """register a function to be called before a component is created.
     The callback is called with arguments:
diff --git a/modules/sd_samplers_kdiffusion.py b/modules/sd_samplers_kdiffusion.py
index f076fc5..ab82c08 100644
--- a/modules/sd_samplers_kdiffusion.py
+++ b/modules/sd_samplers_kdiffusion.py
@@ -8,6 +8,7 @@ from modules import prompt_parser, devices, sd_samplers_common
 from modules.shared import opts, state
 import modules.shared as shared
 from modules.script_callbacks import CFGDenoiserParams, cfg_denoiser_callback
+from modules.script_callbacks import CFGDenoisedParams, cfg_denoised_callback

 samplers_k_diffusion = [
     ('Euler a', 'sample_euler_ancestral', ['k_euler_a', 'k_euler_ancestral'], {}),
@@ -136,6 +137,9 @@ class CFGDenoiser(torch.nn.Module):

             x_out[-uncond.shape[0]:] = self.inner_model(x_in[-uncond.shape[0]:], sigma_in[-uncond.shape[0]:], cond={"c_crossattn": [uncond], "c_concat": [image_cond_in[-uncond.shape[0]:]]})

+        denoised_params = CFGDenoisedParams(x_out, state.sampling_step, state.sampling_steps)
+        cfg_denoised_callback(denoised_params)
+
         devices.test_for_nans(x_out, "unet")

         if opts.live_preview_content == "Prompt":
(END)
```

**Comment by gsgoldma** [comment]
when i ran this extension by itself, i didnt get the error.
when i ran it with my other extensions, i got the error.
i think it's just an extension conflict.

**Comment by beped** [comment]
Same problem here, the patch return this btw:
C:\Users\User\Downloads\stablediffusion\stable-diffusion-webui>git apply --ignore-whitespace extensions/stable-diffusion-webui-two-shot/cfg_denoised_callback-ea9bd9fc.patch
error: patch failed: modules/script_callbacks.py:68
error: modules/script_callbacks.py: patch does not apply
error: patch failed: modules/sd_samplers_kdiffusion.py:8
error: modules/sd_samplers_kdiffusion.py: patch does not apply

**Comment by ddPn08** [comment]
With the webui update the other day, you no longer need to use the patch.  You can use it just by installing it.

**Comment by ShawnFumo** [comment]
I was having this error with a google colab I was using today (latest webui, latest latent couple, etc) and found that it started to work after I removed the embeddings from: https://huggingface.co/nolanaatama/embeddings

**Comment by noahlessard** [comment]
Just for future readers, as of the time writing this, if you are still getting an import error after running the patch commands, it might be because they aren't actually getting applied. The CFG patch worked for me, but the 0001-Adding-after_ui_callback-for-scripts.patch was still needed and wasn't getting applied. I copied it over manually, but this stackoverflow page might help?

https://stackoverflow.com/questions/4770177/git-patch-does-not-apply

**Comment by farmerhu1104** [comment]
> 
I have the same issue like yours, anyone has suggestion?

**Comment by petersk8** [comment]
In my case it was fixed by updating stable diffusion web ui, by executing 'git pull' on the root directory (usually ...\stable-diffusion-webui) it also fixed the slow starting, I'm assuming because of updating old dependencies shared with the plugins I have installed.

I hope this works for you too!
