### ISSUE TITLE
Latent Couple Extension doesn't show up in Automatic 1111 when installed

### ISSUE THREAD

**Issue by letsworktogether12** [opparco/stable-diffusion-webui-two-shot#24]
Hi there,
I am having trouble getting the plugin work. When I install it and restart the webui, it doesn't show up in text2img panel. It's nowhere to be found. What could be the issue?

I am using Stable diffusion 1.5 webui on Runpod.

Thank you!

**Comment by letsworktogether12** [comment]
![Screenshot 2023-03-04 at 21 07 20](https://user-images.githubusercontent.com/35426882/222926574-4393de1c-1adf-4195-ac0e-4958fc578fb9.png)

runpod/stable-diffusion:web-automatic-2.1.15

**Comment by letsworktogether12** [comment]
![Screenshot 2023-03-04 at 21 09 51](https://user-images.githubusercontent.com/35426882/222926630-caa95853-dce9-442e-a4a1-a63fad511479.png)

**Comment by huanggou666** [comment]
same here,  This extension need to apply cfg_denoised  ,I don't know how to that either

**Comment by Norian11** [comment]
This is the error that doesnt leave it work for me neither, lets see if the author knows a solution
Error loading script: two_shot.py
Traceback (most recent call last):
  File "C:\Users\enriq\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\enriq\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\enriq\stable-diffusion-webui\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py", line 11, in <module>
    from modules.script_callbacks import CFGDenoisedParams, on_cfg_denoised
ImportError: cannot import name 'CFGDenoisedParams' from 'modules.script_callbacks' (C:\Users\enriq\stable-diffusion-webui\modules\script_callbacks.py)

**Comment by Norian11** [comment]
I found a solution for the error i wrote above, it looks like in some update of automatic1111 the module script_callbacks changed the name of CFGDenoisedParams to CFGDenoiserParams, just a letter different, so to no touch that file better change the function call in the **_two_shot.py_** using Visual Code or any program, this file is in StableDiffusionUI/extensions/two-shot extension/scripts. Just press Ctrl+F and search the, i think, two or four moments CFGDenoisedParams is mentioned and change it to CFGDenoiserParams.

**Comment by letsworktogether12** [comment]
Norian11, I've changed CFGDenoisedParams to CFGDenoiserParams, but no change. I have no error. The extension when activated never shows up in automatic1111

**Comment by Norian11** [comment]
Sorry I only found that solution for the error i got, if it doesnt shows you any error in the cmd tab after initiated Automatic1111 will be hard to know why happens. Just check that your Automatic1111 is up to date is the only advice can give for that or delete the extension from extensions folder and go again to reinstall it.

**Comment by Norian11** [comment]
Well i just found in internet that i didnt have to change the names in the script (sorry for that, just change it back or reinstall the extension), I just had to run the ``cfg_denoised_callback-ea9bd9fc.patch`` included by the author. I did this in a new cmd tab, just typed ``cd (paste location of your automatic1111 folder)`` press enter and then   ``git apply --ignore-whitespace (location\name.patch of that file mentioned above)``    . If any doubt i guided by the first seconds of this video https://www.youtube.com/watch?v=TYrHBFQPMys&t=142s, he is using other script but works the same to use this cfg one

**Comment by gillopillo** [comment]
right now the script gives this error for me:

I type in an admin console
git apply --ignore-whitespace extensions/stable-diffusion-webui-two-shot/cfg_denoised_callback-ea9bd9fc.patch

And I receive the error
C:\Users\xxxx\stable-diffusion-webui>git apply --ignore-whitespace extensions/stable-diffusion-webui-two-shot/cfg_denoised_callback-ea9bd9fc.patch
error: patch failed: modules/script_callbacks.py:68
error: modules/script_callbacks.py: patch does not apply
error: patch failed: modules/sd_samplers_kdiffusion.py:8
error: modules/sd_samplers_kdiffusion.py: patch does not apply

**Comment by orbithammer** [comment]
I'm getting this error when I try to apply the patch:

error: modules/sd_samplers_kdiffusion.py: No such file or directory

Is there some dependency I'm missing?

**Comment by skymich001** [comment]
I have the same problem, the web ui doesn't show up, when I install the patch i get this error:

C:\Users\slate\stableD\stable-diffusion-webui>git apply --ignore-whitespace extensions/stable-diffusion-webui-two-shot/0001-Adding-after_ui_callback-for-scripts.patch
extensions/stable-diffusion-webui-two-shot/0001-Adding-after_ui_callback-for-scripts.patch:48: new blank line at EOF.
+
error: patch failed: modules/ui.py:969
error: modules/ui.py: patch does not apply

any solution???

**Comment by NoppaiKohai** [comment]
I'm still having this issue and see posts all over Reddit with the same issue

**Comment by LIngerwsk** [comment]
> 

I missed the same error, did you solve it?

**Comment by orbithammer** [comment]
Solved my issue. My webui-user.bat hadn't been updated in a dog's age. Put "git pull" in the bat. Works now

**Comment by joeuser000** [comment]
well after the fact here but i have the same problem with a fresh install on windows and the patch fails with the above errors list? Is there a real solution for this? thx.
