### ISSUE TITLE
ImportError: cannot import name 'on_after_ui' from 'modules.script_callbacks' (/content/stable-diffusion-webui/modules/script_callbacks.py)

### ISSUE THREAD

**Issue by G-force78** [opparco/stable-diffusion-webui-two-shot#31]
Using google collab, launched webUI got this error. I thought it had been merged into auto1111 already?

```
Error loading script: two_shot.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/stable-diffusion-webui/extensions/sd-webui-two-shot/scripts/two_shot.py", line 16, in <module>
    from modules.script_callbacks import CFGDenoisedParams, on_cfg_denoised, on_after_ui
ImportError: cannot import name 'on_after_ui' from 'modules.script_callbacks' (/content/stable-diffusion-webui/modules/script_callbacks.py)
```

**Comment by derron1** [comment]
same error also. ..bump

**Comment by G-force78** [comment]
> same error also. ..bump

Use this one instead
https://github.com/ashen-sensored/stable-diffusion-webui-two-shot
